version: '2'
services:
  db:
      image: postgres:9.6.2
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: pguser
        POSTGRES_PASSWORD: pguser
        POSTGRES_DB: events_db
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
      ports:
        - "9200:9200"
      environment:
        - discovery.type=single-node
        - cluster.name=elasticsearch
        - xpack.security.enabled=false
        - action.auto_create_index=.watches,.triggered_watches,.watcher-history-*,.monitoring-*